
spring:

  profiles:
    active: dev

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@58.155.47.108:1521:orcl
    username: Scott
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


